UI Build 1.4 - update drawable-fixed loading crash
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_75\bin\java.exe'' finished with non-zero exit value 1

Cause- logbg.jpg used for background was to huge in size and resolution.

Solution- Downscaled the image in GIMP